AMBARI-23192. NoClassDefFoundError on Files View on S3 (amagyar)
(cherry picked from commit fd97fe0234bef6dc055873f9acdd344cfbc96d9c)

Change-Id: I2556c638861d0cd9e41d036d63e0c1826492d920